Salon/Salon/Models/UserProfile.cs
namespace Salon.Models
{
    public class UserProfile
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        
        public string Email { get; set; }

    }
}

Salon/Salon/Models/UserProfileView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Salon.Models
{
    public class UserProfileView
    {
        [Required(ErrorMessage = "Please provide your first name", AllowEmptyStrings = false)]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Please provide your last name", AllowEmptyStrings = false)]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Please provide your email", AllowEmptyStrings = false)]
        public string Email { get; set; }
        public string Number { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        [Required(ErrorMessage = "Please provide your password", AllowEmptyStrings = false)]
        public string Password { get; set; }
    }
}

Salon/Salon/Controllers/UserProfileController.cs
using Microsoft.AspNetCore.Mvc;
using Salon.BL.Services.Interface;
using Salon.Model.ViewModels;

namespace Salon.Controllers
{
    public class UserProfileController : Controller
    {
        private readonly IUserAccountService _userAccountService; 
        public UserProfileController(IUserAccountService userAcconuntService)
        {
           _userAccountService = userAcconuntService;
        }

        public async Task<IActionResult> CreateAccount(UserProfileView userProfile)
        {
            return View(userProfile);
        }

        [HttpPost]
        public async Task<IActionResult> SaveAccountAsync(UserProfileView userProfile)
        {

            await _userAccountService.CreateAccount(userProfile);
            return RedirectToAction("Login", "Login");
        }
    }
}

Salon/Salon/Views/UserProfile/CreateAccount.cshtml
@page
@model UserProfileView
@{
    ViewBag.Title = "login";
}
<head>
    <style>
        body {
            background-color: #68437d
}
    </style>
    <link rel="stylesheet" href="~/css/login.css" asp-append-version="true" />

</head>
<body>
    <div class="limiter">
        <div class="container-login">
            <div class="wrap-login">
                <div class="login-form-title">Sign up</div>
                @using (Html.BeginForm("SaveAccount", "UserProfile", FormMethod.Post))
                {
                    <div class="wrap-input">
                        <div> @Html.TextBoxFor(a => a.Email, new { placeholder = "Email", @class = "input-container", required = "required" })</div>
                    </div>
                    <div class="wrap-input">
                        @Html.TextBoxFor(a => a.Password, new { placeholder = "Password", @class = "input-container", required = "required" })
                    </div>
                    <div class="wrap-input">
                        @Html.TextBoxFor(a => a.FirstName, new { placeholder = "First Name", @class = "input-container", required = "required" })
                    </div>
                    <div class="wrap-input">
                        @Html.TextBoxFor(a => a.LastName, new { placeholder = "Last Name", @class = "input-container", required = "required" })
                    </div>
                    <div class="wrap-input">
                        @Html.TextBoxFor(a => a.Street, new { placeholder = "Street", @class = "input-container", required = "required" })
                    </div>
                    <div class="wrap-input">
                        @Html.TextBoxFor(a => a.Number, new { placeholder = "Number", @class = "input-container", required = "required" })
                    </div>
                    <div class="wrap-input">
                        @Html.TextBoxFor(a => a.City, new { placeholder = "City", @class = "input-container", required = "required" })
                    </div>
                    <div class="wrap-input">
                        @Html.TextBoxFor(a => a.Country, new { placeholder = "Country", @class = "input-container", required = "required" })
                    </div>
                    <div>
                        <div class="container-login-form-btn">
                            
                                <button class="login-form-btn">
                                    Sign up
                                </button>
                          
                        </div>
                    </div>

                }
            </div>
        </div>
    </div>
</body>